# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название планеты')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=640, verbose_name='Текст вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=64, verbose_name='Ответ')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedis.Candidate', verbose_name='Исполнитель задания')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedis.Questions')),
            ],
        ),
        migrations.AddField(
            model_name='jedi',
            name='planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedis.Planet', verbose_name='Планета проживания'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedis.Jedi'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='planet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jedis.Planet', verbose_name='Planet'),
        ),
        migrations.AddField(
            model_name='auth',
            name='jedi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedis.Jedi', verbose_name='Джедай'),
        ),
    ]
