# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='question',
            field=models.CharField(default='', max_length=64, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='results',
            name='result',
            field=models.CharField(default='', max_length=64, verbose_name='Ответ'),
        ),
    ]
